version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
      - mongodb
    networks:
      default:
      internal:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '5080:5080'
      - '5081:5081'
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/collegeEventsDB
      - PYTHON_SERVER_URL=http://localhost:5081/api
      - PORT=5080
    networks:
      default:
      internal:
    volumes:
      - ./backend/uploads:/app/uploads

  mongodb:
    image: mongo:8
    container_name: mongodb
    networks:
      internal:
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

networks:
  default:
  internal:
    internal: true
