version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bills-frontend
    ports:
      - '8071:3000'
    depends_on:
      - backend
      - mongodb
    networks:
      default:
      internal:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bills-backend
    ports:
      - '8072:5080'
      - '8073:5081'
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://bills-mongodb:27017/collegeEventsDB
      - PYTHON_SERVER_URL=http://localhost:8073/api
      - PORT=5080
      - JWT_SECRET=12idawd88j2be2h71h7q2he27qq2etq2h1e
    networks:
      default:
      internal:
    volumes:
      - ./backend/uploads:/app/uploads

  mongodb:
    image: mongo:8
    container_name: bills-mongodb
    networks:
      internal:
    volumes:
      - ../db:/data/db

networks:
  default:
  internal:
    internal: true
